### ISSUE TITLE
Unable to install package using pip3 because 

### ISSUE THREAD

**Issue by aldencolerain** [deeplook/sparklines#26]
Package can't be installed using pip3 because the encoding is not specified when reading readme file for long description in setup.py

```
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-tyqk0xlz-build/setup.py", line 31, in <module>
        long_description=open('README.rst', errors='replace').read().decode(),
    AttributeError: 'str' object has no attribute 'decode'

```

**Comment by aldencolerain** [comment]
Closed with #25
