### ISSUE TITLE
Install fails due to missing `future` package

### ISSUE THREAD

**Issue by jrasky** [deeplook/sparklines#27]
Hello, I got the following trace when installing sparklines:

```
jerome@excalibur:~$ pip3 install sparklines
Collecting sparklines
  Using cached sparklines-0.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zv/y0ngqtr94zn_t2ncr7lf0dkw0000gn/T/pip-build-772ospb5/sparklines/setup.py", line 4, in <module>
        from sparklines.sparklines import __version__
      File "/private/var/folders/zv/y0ngqtr94zn_t2ncr7lf0dkw0000gn/T/pip-build-772ospb5/sparklines/sparklines/__init__.py", line 7, in <module>
        from sparklines.sparklines import *
      File "/private/var/folders/zv/y0ngqtr94zn_t2ncr7lf0dkw0000gn/T/pip-build-772ospb5/sparklines/sparklines/sparklines.py", line 16, in <module>
        from future.builtins import round # bankers' rounding for Python 2
    ModuleNotFoundError: No module named 'future'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/zv/y0ngqtr94zn_t2ncr7lf0dkw0000gn/T/pip-build-772ospb5/sparklines/
```

Installing `future` separately fixed the issue, but shouldn't that be part of a requirements.txt for this package? Am I just doing something wrong?

**Comment by aquatix** [comment]
Current version in pip is still uninstallable? Got this problem today trying to install with Python 3.6

**Comment by deeplook** [comment]
I've just pushed 0.4.2 to https://pypi.org/project/sparklines/ and will close this within a few days in the absence of any related issues to it.
