### ISSUE TITLE
requirement for future not specified in package

### ISSUE THREAD

**Issue by apierleoni** [deeplook/sparklines#6]
Hi, when trying to install version 0.4.1  on python 2.7 from pip, I got an error about the missing future package.
It should probably be specified in the package requirements.

**Comment by deeplook** [comment]
It is listed in `setup.py`. How did you install it exactly?

**Comment by aldencolerain** [comment]
@deeplook I actually had the same issue.  It probably shouldn't be closed.
```
Collecting sparklines
  Downloading sparklines-0.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-e1vz5wcf/sparklines/setup.py", line 4, in <module>
        from sparklines.sparklines import __version__
      File "/tmp/pip-build-e1vz5wcf/sparklines/sparklines/__init__.py", line 7, in <module>
        from sparklines.sparklines import *
      File "/tmp/pip-build-e1vz5wcf/sparklines/sparklines/sparklines.py", line 16, in <module>
        from future.builtins import round # bankers' rounding for Python 2
    ImportError: No module named 'future'
```

I fixed it by installing the future module `pip install future` and then trying again.
